"""Pull Request creation phase."""

import re
import subprocess
from pathlib import Path
from typing import Optional

from cafe.agents.manager import AgentManager
from cafe.core.git import GitOperations
from cafe.core.permission import PermissionHandler
from cafe.core.phase import Phase
from cafe.core.types import PhaseResult, PhaseStatus, WorkflowMode


class PRPhase(Phase):
    """Phase 5: Pull Request creation."""

    def __init__(
        self,
        agent_manager: AgentManager,
        permission_handler: PermissionHandler,
        git_ops: GitOperations,
        spec_file: str,
        workflow_mode: WorkflowMode,
        issue_id: Optional[str] = None,
        issue_name: Optional[str] = None,
        draft: bool = True,
        custom_title: Optional[str] = None,
        custom_body: Optional[str] = None,
        interactive: bool = True,
    ) -> None:
        """Initialize PR phase.

        Args:
            agent_manager: Agent manager
            permission_handler: Permission handler
            git_ops: Git operations
            spec_file: Path to spec file
            workflow_mode: Workflow mode (local or github)
            issue_id: GitHub issue ID (required for github mode)
            issue_name: Issue name (for local mode branch naming)
            draft: Create as draft PR (default: True)
            custom_title: Custom PR title (None for auto-generation)
            custom_body: Custom PR body (None for auto-generation)
            interactive: Enable interactive mode (default: True)
        """
        super().__init__(interactive=interactive)

        self.agent_manager = agent_manager
        self.permission_handler = permission_handler
        self.git_ops = git_ops
        self.spec_file = spec_file
        self.workflow_mode = workflow_mode
        self.issue_id = issue_id
        self.issue_name = issue_name
        self.draft = draft
        self.custom_title = custom_title
        self.custom_body = custom_body

    def execute(self) -> PhaseResult:
        """Execute PR creation phase.

        Returns:
            Phase result
        """
        try:
            # Validate inputs
            if self.workflow_mode == WorkflowMode.GITHUB and not self.issue_id:
                return PhaseResult(
                    status=PhaseStatus.FAILED,
                    message="GitHub mode requires issue_id",
                )

            if self.workflow_mode == WorkflowMode.LOCAL:
                # Check requirements file exists
                req_path = Path(self.spec_file)
                if not req_path.exists():
                    return PhaseResult(
                        status=PhaseStatus.FAILED,
                        message=f"Spec file not found: {self.spec_file}",
                    )

            # Get branch name
            branch_name = self._get_branch_name()

            # Push branch to remote
            self.git_ops.push(branch_name, set_upstream=True)

            # Prepare PR directory
            spec_path = Path(self.spec_file)
            issue_name = spec_path.parent.parent.name
            pr_dir = spec_path.parent.parent / "pr"
            pr_dir.mkdir(parents=True, exist_ok=True)

            title_file = pr_dir / "title.txt"
            body_file = pr_dir / "body.md"

            # Determine what needs to be generated by agent
            need_title = self.custom_title is None
            need_body = self.custom_body is None

            # Write custom values if provided
            if self.custom_title:
                title_file.write_text(self.custom_title)
            if self.custom_body:
                body_file.write_text(self.custom_body)

            # Generate missing content using agent
            if need_title or need_body:
                self._generate_pr_content(generate_title=need_title, generate_body=need_body)

            # Read PR title and body from files (unified approach)
            pr_title = self._get_pr_title()
            pr_body = self._get_pr_body()

            # Create PR using gh CLI
            pr_number, pr_url = self._create_pr(pr_title, pr_body, branch_name)

            return PhaseResult(
                status=PhaseStatus.COMPLETED,
                message=f"Pull Request #{pr_number} created successfully",
                data={"pr_number": pr_number, "pr_url": pr_url, "branch": branch_name},
            )

        except FileNotFoundError as e:
            return PhaseResult(
                status=PhaseStatus.FAILED,
                message=f"gh CLI not found: {e}",
            )
        except Exception as e:
            return PhaseResult(
                status=PhaseStatus.FAILED,
                message=f"PR phase failed: {e}",
            )

    def _get_branch_name(self) -> str:
        """Get branch name based on workflow mode.

        Returns:
            Branch name
        """
        if self.workflow_mode == WorkflowMode.GITHUB:
            return f"issue-{self.issue_id}"
        else:
            # Use issue_name directly if provided
            if self.issue_name:
                return self.issue_name

            # Fallback: Extract from requirements filename
            # e.g., "20250101-feature.md" -> "feature"
            filename = Path(self.spec_file).stem
            # Remove date prefix if exists
            match = re.match(r"^\d{8}-(.+)$", filename)
            if match:
                return match.group(1)
            return filename

    def _generate_pr_content(self, generate_title: bool = True, generate_body: bool = True) -> None:
        """Generate PR title and/or body using agent.

        Args:
            generate_title: Whether to generate title (default: True)
            generate_body: Whether to generate body (default: True)

        Agent writes to:
        - .cafe/issues/{issue_name}/pr/title.txt (if generate_title=True)
        - .cafe/issues/{issue_name}/pr/body.md (if generate_body=True)
        """
        if not generate_title and not generate_body:
            return  # Nothing to generate

        # Derive issue name and pr directory
        spec_path = Path(self.spec_file)
        issue_name = spec_path.parent.parent.name
        pr_dir = spec_path.parent.parent / "pr"
        pr_dir.mkdir(parents=True, exist_ok=True)

        title_file = pr_dir / "title.txt"
        body_file = pr_dir / "body.md"

        # Derive plan file path
        plan_file = spec_path.parent.parent / "plan" / "plan.md"

        # Get commits for context
        main_branch = self.git_ops.get_main_branch()
        commits = self.git_ops.get_commits_between(
            base=f"origin/{main_branch}", head="HEAD"
        )

        # Build issue reference for GitHub mode
        issue_instruction = f"\n- 在 body.md 開頭加上 `Closes #{self.issue_id}`" if self.workflow_mode == WorkflowMode.GITHUB else ""

        # Build tasks based on what needs to be generated
        tasks = []
        if generate_title:
            tasks.append(f"""1. 將 PR title 寫入 `{title_file}`
   - 一行，簡潔明確（不超過 80 字元）
   - 描述這個 PR 做了什麼
   - 範例：Add user authentication with OAuth2 support""")

        if generate_body:
            task_num = "2" if generate_title else "1"
            tasks.append(f"""{task_num}. 將 PR description 寫入 `{body_file}`（Markdown 格式）
   - ## Summary - 簡要說明（2-3 句話）
   - ## Changes - 主要變更（bullet points）
   - ## Test Plan - 如何測試{issue_instruction}""")

        tasks_str = "\n\n".join(tasks)

        # Determine what is being generated for the prompt
        if generate_title and generate_body:
            what_to_generate = "title 和 description"
            status_desc = "PR title 和 body 已產生完成"
        elif generate_title:
            what_to_generate = "title"
            status_desc = "PR title 已產生完成"
        else:
            what_to_generate = "description"
            status_desc = "PR body 已產生完成"

        # Generate prompt for agent
        prompt = f"""你需要為這個 Pull Request 產生 {what_to_generate}。

**需求規格：** {self.spec_file}
**實作計畫：** {plan_file}

**Commits：**
{commits}

**任務：**
{tasks_str}

完成後請回傳 CAFE_CONFIRMED。
"""

        # Execute agent
        from cafe.core.status_codes import PhaseStatusCode, generate_status_code_prompt

        status_code_prompt = generate_status_code_prompt(
            valid_codes=[PhaseStatusCode.CONFIRMED],
            descriptions={
                PhaseStatusCode.CONFIRMED: status_desc,
            },
        )

        full_prompt = prompt + "\n\n" + status_code_prompt

        # Set allowed tools for writing
        allowed_tools = ["read"]
        if generate_title:
            allowed_tools.append(f"write({title_file})")
        if generate_body:
            allowed_tools.append(f"write({body_file})")

        response, _, _, _ = self.agent_manager.execute(
            agent_name="David",
            prompt=full_prompt,
            allowed_tools=allowed_tools,
        )

        # Verify requested files were created
        if generate_title and not title_file.exists():
            raise RuntimeError("Agent failed to generate PR title file")
        if generate_body and not body_file.exists():
            raise RuntimeError("Agent failed to generate PR body file")

    def _get_pr_title(self) -> str:
        """Read PR title from agent-generated or user-provided file.

        Returns:
            PR title
        """
        spec_path = Path(self.spec_file)
        issue_name = spec_path.parent.parent.name
        title_file = spec_path.parent.parent / "pr" / "title.txt"

        return title_file.read_text().strip()

    def _get_pr_body(self) -> str:
        """Read PR body from agent-generated or user-provided file.

        Returns:
            PR body
        """
        spec_path = Path(self.spec_file)
        issue_name = spec_path.parent.parent.name
        body_file = spec_path.parent.parent / "pr" / "body.md"

        return body_file.read_text().strip()

    def _create_pr(self, title: str, body: str, branch_name: str) -> tuple[str, str]:
        """Create PR using gh CLI.

        Args:
            title: PR title
            body: PR body
            branch_name: Branch name

        Returns:
            Tuple of (PR number, PR URL)

        Raises:
            subprocess.CalledProcessError: If gh pr create fails
        """
        # Build gh pr create command
        cmd = ["gh", "pr", "create", "--title", title, "--body", body]

        # Add --draft flag if draft mode is enabled
        if self.draft:
            cmd.append("--draft")

        # Create PR
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=False,
        )

        if result.returncode != 0:
            raise RuntimeError(f"gh pr create failed: {result.stderr}")

        # Extract PR number from URL
        # Expected format: https://github.com/user/repo/pull/123
        pr_url = result.stdout.strip()
        match = re.search(r"/pull/(\d+)", pr_url)
        if match:
            return match.group(1), pr_url

        raise RuntimeError(f"Failed to extract PR number from: {pr_url}")
