#!/usr/bin/env python3
"""End-to-end test for spec phase using real CLI command with LLM as user.

This test verifies the complete spec phase workflow:
1. Calls the actual `aaf spec` CLI command
2. Uses Claude LLM to simulate user responses
3. Verifies multi-iteration conversation flow
4. Ensures requirements are confirmed within 5 iterations

Note: This test requires:
- Claude CLI installed and configured
- Network connection for LLM API calls
- Costs money (small amount) due to API usage
"""

import pytest
import subprocess
import json
from pathlib import Path


def get_llm_response(spec_content: str) -> str:
    """Get LLM user response to PM's questions.

    Args:
        spec_content: The spec.md content with PM's questions

    Returns:
        User's response generated by Claude LLM
    """
    prompt = f"""你是 aaf spec 指令的 QA，你要假裝自己是用戶來測試每一輪的結果是否符合預期。上一輪 PM 整理的需求如下：

{spec_content}

如果有「## 待釐清的問題」，簡潔回答。沒問題就說「沒問題」。
用繁體中文，直接回答，不要其他說明。"""

    result = subprocess.run(
        ["claude", "-p", prompt, "--output-format", "json"],
        capture_output=True, text=True
    )
    data = json.loads(result.stdout)
    return data.get("result", "")


@pytest.mark.e2e
@pytest.mark.slow
def test_spec_cli_with_llm_user():
    """End-to-end test: aaf spec command with LLM simulating user.

    This test:
    - Runs the actual `aaf spec` CLI command (not mocked)
    - Uses Claude LLM to automatically respond to PM's questions
    - Verifies the conversation completes within 5 iterations
    - Checks that final status is CONFIRMED
    """
    # Clean up from previous test runs
    test_files = ["test_myip_e2e.md", ".aaf"]
    for f in test_files:
        p = Path(f)
        if p.exists():
            import shutil
            shutil.rmtree(p) if p.is_dir() else p.unlink()

    # Initial user story
    user_story = "身為開發者，我想要有一個指令 `myip` 可以顯示我的內網 IP 和外網 IP，以便我可以快速複製貼上到別的地方"

    max_iterations = 5
    test_passed = False

    for i in range(1, max_iterations + 1):
        print("=" * 70)
        print(f"Iteration {i}")
        print("=" * 70)

        if i == 1:
            user_input = user_story
        else:
            # Check status.json from previous iteration
            status_file = Path(".aaf/issues/test_myip_e2e/spec/status.json")
            assert status_file.exists(), f"status.json not found after iteration {i-1}"

            with open(status_file) as f:
                status_data = json.load(f)

            status = status_data.get("status")
            status_code = status_data.get("status_code")

            print(f"Previous status: {status}, code: {status_code}")

            # Check if completed
            if status == "completed" and status_code == "CONFIRMED":
                print("✅ CONFIRMED - Spec complete!")

                # Show final spec
                spec_file = Path(".aaf/issues/test_myip_e2e/spec/history/spec.md")
                if spec_file.exists():
                    print("\nFinal Spec:")
                    print(spec_file.read_text())
                test_passed = True
                break

            # If need clarification, get LLM response
            if status_code == "NEED_CLARIFICATION":
                spec_file = Path(".aaf/issues/test_myip_e2e/spec/history/spec.md")
                assert spec_file.exists(), "spec.md not found"

                spec_content = spec_file.read_text()

                print("🤖 Getting LLM response...")
                user_input = get_llm_response(spec_content)
                print(f"Response: {user_input[:200]}...")
            else:
                pytest.fail(f"Unexpected status: {status}")

        print()
        print(f"Calling: aaf spec test_myip_e2e.md --non-interactive")

        # Call aaf spec
        result = subprocess.run(
            ["aaf", "spec", "test_myip_e2e.md", "--non-interactive"],
            input=user_input + "\nEND\n",
            capture_output=True, text=True
        )

        print(f"Exit code: {result.returncode}")
        if result.returncode != 0:
            print("STDERR:", result.stderr)

        # Show token usage if available
        if "Token Usage" in result.stdout:
            print(result.stdout)

        # Check new status
        status_file = Path(".aaf/issues/test_myip_e2e/spec/status.json")
        if status_file.exists():
            with open(status_file) as f:
                status_data = json.load(f)
            current_iteration = status_data.get('iteration', i)
            print(f"New status: {status_data.get('status')}, code: {status_data.get('status_code')}")
            print(f"Current iteration: {current_iteration}")

            # Safety check: if iteration exceeds max_iterations, something is wrong
            assert current_iteration <= max_iterations, \
                f"Exceeded max iterations ({max_iterations}), current: {current_iteration}"
        else:
            pytest.fail("status.json not created!")

        print()

    # Verify test completed successfully
    assert test_passed, f"Test failed: reached {max_iterations} iterations without CONFIRMED status"

    # Cleanup
    import shutil
    shutil.rmtree(".aaf")
    Path("test_myip_e2e.md").unlink()

    print("=" * 70)
    print("✅ E2E TEST PASSED: Spec confirmed successfully!")
    print("=" * 70)


if __name__ == "__main__":
    # Allow running directly for manual testing
    pytest.main([__file__, "-v", "-s"])
