"""Bounded agent guidance and deterministic registry-derived documentation."""

from .models import Registry
from .resolver import View

START = "<!-- cafe-runtime-constraints:start -->"
END = "<!-- cafe-runtime-constraints:end -->"


def describe(boundary):
    if boundary is None:
        return "unverified; do not assert an exact external limit"
    if boundary.kind == "semantic":
        return boundary.rule
    return (
        "; ".join(f"{q.name}={q.value} {q.unit}" for q in boundary.limits)
        + "; "
        + boundary.semantics
    )


def render_prompt(view: View) -> str:
    entries = [e for e in view.entries if e.status == "active"]
    if not entries:
        return ""
    lines = [START, "Runtime constraints (guidance grants no additional authority):"]
    for e in entries:
        lines.append(
            f"- [{e.id}] ({e.enforcement}, {e.validity}) {describe(e.boundary)} "
            f"Action: {e.record.mitigation} Escalation: {e.record.escalation} "
            f"Authority: {e.record.permission_boundary}"
        )
    lines.extend(
        [
            "Record applicable IDs and chosen action in your execution plan; include IDs in interruption handoffs/recovery requests. "
            "Verify progress is CAFE-observable, preserve child exit status, and collect separate completion evidence. "
            "If bounded work or supported visible progress is unavailable, declare assistance before starting in the existing output/handoff:",
            '```json\n{"kind":"constraint_assistance","constraint_ids":["<applicable ID>"],"workload":"<work>",'
            '"reason":"<boundary>","requested_support":"<support>","completion_evidence":"<required proof>"}\n```',
            "All fields must be non-empty; IDs must be unique. This declaration records intent, not approval or a capability request. "
            "Use only existing authorized handoff routes. Inspect details with cafe constraints show <ID> --json.",
            END,
        ]
    )
    block = "\n".join(lines)
    if len(block.encode("utf-8")) > 8192:
        ids = ", ".join(e.id for e in entries)[:512]
        raise ValueError(
            f"Runtime constraints exceed 8 KiB: {ids}; inspect cafe constraints list --json"
        )
    return block


def replace_prompt_block(prompt: str, view: View) -> str:
    # Replace our own complete block; do not discard any user text outside it.
    while START in prompt:
        left, remainder = prompt.split(START, 1)
        if END not in remainder:
            raise ValueError("Incomplete runtime constraints block")
        _, right = remainder.split(END, 1)
        prompt = left + right
    block = render_prompt(view)
    return (block + "\n\n" + prompt.strip()).strip()


def render_docs(registry: Registry) -> str:
    lines = [
        "<!-- Generated by cafe constraints docs render; edit the registry, not this page. -->",
        "# Known Constraints",
        "",
        "Package-owned facts and guidance confer no execution or advancement authority.",
        "",
    ]
    for title, status, enforcement in [
        ("Runtime limitations", "active", "runtime"),
        ("Policy boundaries", "active", "policy"),
        ("External/provider facts", "active", "provider-host"),
        ("Deprecated history", "deprecated", None),
        ("Resolved history", "resolved", None),
    ]:
        lines.extend([f"## {title}", ""])
        selected = [
            e
            for e in registry.entries
            if e.status == status and (enforcement is None or e.enforcement == enforcement)
        ]
        if not selected:
            lines.extend(["No entries.", ""])
        for e in sorted(selected, key=lambda e: e.id):
            lines.extend(
                [
                    f'<a id="{e.id}"></a>',
                    f"### `{e.id}` — {e.title}",
                    "",
                    f"Status: {e.status}; enforcement: {e.enforcement}; observed CAFE: {e.lifecycle.observed_version}.",
                    "",
                    f"Lifecycle: introduced={e.lifecycle.introduced or 'unknown'}, changed={e.lifecycle.changed or 'unknown'}, resolved={e.lifecycle.resolved or 'N/A'}.",
                    e.lifecycle.historical_evidence,
                    "",
                ]
            )
            for v in e.variants:
                lines.extend(
                    [
                        f"- Scope: `{v.scope.model_dump_json(exclude_defaults=True)}`. {describe(v.boundary)}",
                        "",
                    ]
                )
            source_links = "; ".join(
                f"[{s}](../{s.split(':')[0]})" if not s.startswith("http") else f"[source]({s})"
                for s in e.sources
            )
            lines.extend(
                [
                    f"Trigger: {e.trigger}",
                    f"Impact: {e.impact}",
                    "",
                    f"Detection: {e.detection}",
                    f"Sources: {source_links}",
                    "",
                    f"Mitigation: {e.mitigation}",
                    f"Escalation: {e.escalation}",
                    f"Permission boundary: {e.permission_boundary}",
                    "",
                ]
            )
            if e.verification:
                lines.extend([f"Verification: {e.verification.model_dump_json()}", ""])
            if e.related_issues:
                lines.extend(["Related: " + ", ".join(e.related_issues), ""])
            if e.replacement_behavior or e.lifecycle.resolution_evidence:
                lines.extend([e.replacement_behavior or e.lifecycle.resolution_evidence, ""])
    return "\n".join(lines).rstrip() + "\n"
