"""The small public surface for issue-scoped Manager kickoff contracts."""

from .api import (
    ActivateConfirmedContract,
    ActivationResult,
    ManagerContractMissingError,
    ManagerContractUnsafeError,
    ManagerEntryRequest,
    ManagerEntryResult,
    ManagerSettingsUpdateResult,
    EventCallbackPolicy,
    EventCallbackRequest,
    Freshness,
    LegacyAdoptionRequest,
    LegacyAdoptionResult,
    ReplaceConfirmedContract,
    ReplacementResult,
    activate_confirmed_contract,
    adopt_legacy_contract,
    evaluate_manager_entry,
    event_callback_projection,
    replace_confirmed_contract,
    update_manager_settings,
)

__all__ = [
    "ActivateConfirmedContract",
    "ActivationResult",
    "ManagerContractMissingError",
    "ManagerContractUnsafeError",
    "ManagerEntryRequest",
    "ManagerEntryResult",
    "ManagerSettingsUpdateResult",
    "EventCallbackPolicy",
    "EventCallbackRequest",
    "Freshness",
    "LegacyAdoptionRequest",
    "LegacyAdoptionResult",
    "ReplaceConfirmedContract",
    "ReplacementResult",
    "activate_confirmed_contract",
    "adopt_legacy_contract",
    "evaluate_manager_entry",
    "event_callback_projection",
    "replace_confirmed_contract",
    "update_manager_settings",
]
